"""governance: approval requests, decisions and policy

Revision ID: 15f000d3ab7d
Revises: 7e259250c53b
Create Date: 2026-08-14 20:45:04.326684+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '15f000d3ab7d'
down_revision: str | None = '7e259250c53b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_decisions')),
    sa.UniqueConstraint('request_id', 'approver_id', name='uq_approval_decisions_one_each')
    )
    op.create_index('ix_approval_decisions_request', 'approval_decisions', ['request_id'], unique=False)
    op.create_table('approval_policies',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_approval_policies'))
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('artifact_ref', sa.String(length=512), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approvers_required', sa.Integer(), nullable=False),
    sa.Column('withdrawn_reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('approvers_required >= 1', name=op.f('ck_approval_requests_approvers_required_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index('ix_approval_requests_workspace_status', 'approval_requests', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_approval_requests_open_artifact', 'approval_requests', ['workspace_id', 'artifact_ref'], unique=True, postgresql_where=sa.text("status IN ('draft', 'review')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_approval_requests_open_artifact', table_name='approval_requests', postgresql_where=sa.text("status IN ('draft', 'review')"))
    op.drop_index('ix_approval_requests_workspace_status', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_table('approval_policies')
    op.drop_index('ix_approval_decisions_request', table_name='approval_decisions')
    op.drop_table('approval_decisions')
    # ### end Alembic commands ###
