"""jobs: last progress timestamp for stall detection

Revision ID: 2326971b0a0f
Revises: df69eba49586
Create Date: 2026-08-14 18:39:23.948299+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2326971b0a0f'
down_revision: str | None = 'df69eba49586'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('progress_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'progress_at')
    # ### end Alembic commands ###
