"""modelling: factors and models

`02` FR-MODEL-1/7 versions a Factor independently of any Model, and `02` §4.8 makes a
Model immutable once fitted (R2). Two constraints carry rules the type system also states,
because a type is a rule about one process and a constraint survives a direct `UPDATE`:

* `uq_models_spec_hash` — FR-MODEL-66 returns the existing model rather than fitting the
  same specification twice. Uniqueness is what makes that a fact rather than a race.
* `fitted_model_has_a_fit_result` — a model at `fitted` or beyond without its numbers
  would be a version something could reference and nothing could score

Revision ID: 3ab4db71d0e8
Revises: a1b2c3d4e5f6
Create Date: 2026-08-15 18:10:04.968506+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3ab4db71d0e8'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_factors_factor_version_starts_at_one')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factors')),
    sa.UniqueConstraint('workspace_id', 'slug', 'version', name='uq_factors_slug_version')
    )
    op.create_index('ix_factors_dataset', 'factors', ['workspace_id', 'dataset_id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('model_family_slug', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spec_hash', sa.String(length=71), nullable=False),
    sa.Column('fit_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_model_id', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'archived') OR fit_result IS NOT NULL", name=op.f('ck_models_fitted_model_has_a_fit_result')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_models_model_version_starts_at_one')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('workspace_id', 'model_family_slug', 'version', name='uq_models_family_version'),
    sa.UniqueConstraint('workspace_id', 'spec_hash', name='uq_models_spec_hash')
    )
    op.create_index('ix_models_dataset_version', 'models', ['workspace_id', 'dataset_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_models_dataset_version', table_name='models')
    op.drop_table('models')
    op.drop_index('ix_factors_dataset', table_name='factors')
    op.drop_table('factors')
    # ### end Alembic commands ###
