"""data: validation reports, profiles, rules, acknowledgements

Revision ID: 3e8d06eedb28
Revises: fd8546e9bba3
Create Date: 2026-08-14 23:21:26.194211+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3e8d06eedb28'
down_revision: str | None = 'fd8546e9bba3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('row_count >= 0', name=op.f('ck_profiles_profile_row_count_is_not_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_index('ix_profiles_version', 'profiles', ['dataset_version_id', 'created_at'], unique=False)
    op.create_table('validation_acknowledgements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(justification) > 0', name=op.f('ck_validation_acknowledgements_justification_is_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_acknowledgements')),
    sa.UniqueConstraint('report_id', 'rule_id', name='uq_acknowledgement_scope')
    )
    op.create_index('ix_acknowledgements_version', 'validation_acknowledgements', ['dataset_version_id'], unique=False)
    op.create_table('validation_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_version', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('overall', sa.String(length=24), nullable=False),
    sa.Column('rule_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('warn_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('finished_at >= started_at', name=op.f('ck_validation_reports_report_is_ordered')),
    sa.CheckConstraint('rule_count >= fail_count + warn_count + error_count', name=op.f('ck_validation_reports_counts_do_not_exceed_the_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_reports'))
    )
    op.create_index('ix_validation_reports_version', 'validation_reports', ['dataset_version_id', 'created_at'], unique=False)
    op.create_table('validation_rule_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_validation_rule_sets_rule_set_version_starts_at_one')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_rule_sets')),
    sa.UniqueConstraint('workspace_id', 'slug', 'version', name='uq_rule_set_version')
    )
    op.create_table('validation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('layer', sa.String(length=32), nullable=False),
    sa.Column('check', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('authored_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('dry_run_report_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'approved' OR (approved_by IS NOT NULL AND approved_by <> authored_by AND dry_run_report_id IS NOT NULL)", name=op.f('ck_validation_rules_approved_rule_has_a_dry_run_and_a_separate_approver')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_validation_rules_rule_version_starts_at_one')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_rules')),
    sa.UniqueConstraint('workspace_id', 'slug', 'version', name='uq_validation_rule_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_rules')
    op.drop_table('validation_rule_sets')
    op.drop_index('ix_validation_reports_version', table_name='validation_reports')
    op.drop_table('validation_reports')
    op.drop_index('ix_acknowledgements_version', table_name='validation_acknowledgements')
    op.drop_table('validation_acknowledgements')
    op.drop_index('ix_profiles_version', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
