"""job logs

Revision ID: 45172b9caf46
Revises: 2326971b0a0f
Create Date: 2026-08-14 18:55:59.432767+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '45172b9caf46'
down_revision: str | None = '2326971b0a0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('logger', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_logs')),
    sa.UniqueConstraint('seq', name=op.f('uq_job_logs_seq'))
    )
    op.create_index('ix_job_logs_job_id_seq', 'job_logs', ['job_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_logs_job_id_seq', table_name='job_logs')
    op.drop_table('job_logs')
    # ### end Alembic commands ###
