"""data: reference tables and subject purges

FR-DATA-29 requires half-open effective-dated intervals with no overlap per key. That is
enforced by a PostgreSQL **exclusion constraint** over a daterange, not by application
code: overlapping intervals mean an "as at" lookup has two answers, and which one a quote
receives would depend on row order — a rating difference nobody could reproduce.

The constraint needs `btree_gist`, because it mixes an equality test on the key with an
overlap test on the range. That combination was verified against PostgreSQL 16 during
Phase 0 research before this table existed.

Revision ID: 5bfde19b6085
Revises: 902093cc0437
Create Date: 2026-08-14 22:46:41.497861+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5bfde19b6085'
down_revision: str | None = '902093cc0437'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


EXCLUSION = """
ALTER TABLE reference_rows
  ADD CONSTRAINT ex_reference_rows_no_overlap
  EXCLUDE USING gist (
    reference_table_version_id WITH =,
    key WITH =,
    daterange(effective_from, effective_to, '[)') WITH &&
  )
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_table_version_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_reference_rows_effective_interval_is_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_rows'))
    )
    op.create_index('ix_reference_rows_version_key', 'reference_rows', ['reference_table_version_id', 'key'], unique=False)
    op.create_table('reference_table_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('reference_table_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_reference_table_versions_reference_version_starts_at_one')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_table_versions')),
    sa.UniqueConstraint('reference_table_id', 'version', name='uq_reference_versions')
    )
    op.create_table('reference_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('key_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_tables')),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_reference_tables_workspace_slug')
    )
    op.create_table('subject_purges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('subject_token', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('versions_affected', sa.Integer(), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_purges'))
    )
    op.create_index('ix_subject_purges_dataset', 'subject_purges', ['workspace_id', 'dataset_id'], unique=False)
    # ### end Alembic commands ###

    # btree_gist supplies the `=` operator class for gist, which the mixed constraint needs.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(EXCLUSION)


def downgrade() -> None:
    op.execute("ALTER TABLE reference_rows DROP CONSTRAINT IF EXISTS ex_reference_rows_no_overlap")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subject_purges_dataset', table_name='subject_purges')
    op.drop_table('subject_purges')
    op.drop_table('reference_tables')
    op.drop_table('reference_table_versions')
    op.drop_index('ix_reference_rows_version_key', table_name='reference_rows')
    op.drop_table('reference_rows')
    # ### end Alembic commands ###
