"""data: ingestion runs

Revision ID: 902093cc0437
Revises: 3fc32ae3c77c
Create Date: 2026-08-14 21:29:54.801530+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '902093cc0437'
down_revision: str | None = '3fc32ae3c77c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('source_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('reject_sample', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bytes_read', sa.BigInteger(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('library_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rows_read >= 0 AND rows_written >= 0 AND rows_rejected >= 0', name=op.f('ck_ingestion_runs_row_counts_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index('ix_ingestion_runs_dataset', 'ingestion_runs', ['dataset_id'], unique=False)
    op.create_index('uq_ingestion_runs_idempotency', 'ingestion_runs', ['workspace_id', 'dataset_id', 'idempotency_key', 'source_fingerprint'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ingestion_runs_idempotency', table_name='ingestion_runs', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_ingestion_runs_dataset', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
