"""platform core: jobs, audit events, outbox

Creates the three tables WK-658 is built on, and — more importantly — the enforcement that
makes `audit_events` genuinely append-only (FR-370, `06` R2).

That enforcement is in three layers, because each one is bypassable by the layer above it
and measurement showed exactly where:

1. **Privileges.** The application connects as `gip_app`, which is *not* the table owner
   and holds `SELECT, INSERT` on `audit_events` and nothing else. This is what FR-370
   specifies, and it stops the application.

   Revoking from the owner does **not** work — verified against PostgreSQL 16: after
   `REVOKE UPDATE, DELETE ... FROM <owner>`, an owner `UPDATE` still reported `UPDATE 1`.
   Ownership carries implicit privileges. So the app must be a separate role, or the
   requirement is decorative.

2. **Triggers.** A row trigger rejects `UPDATE` and `DELETE` even for the owner, covering
   operator error and a mistaken `psql` session. A **statement** trigger is needed as well:
   row triggers do not fire on `TRUNCATE`, and without it a single `TRUNCATE audit_events`
   silently empties the log — also verified, before this migration existed.

3. **The hash chain** (FR-372), which detects what neither of the above can prevent.
   `SET session_replication_role = replica` disables triggers outright and a superuser can
   re-grant any privilege; both were confirmed to bypass layers 1 and 2. The chain is why
   the spec says tampering is *detectable* rather than impossible.

Revision ID: df53696a2682
Revises: 
Create Date: 2026-08-14 17:47:53.931405+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'df53696a2682'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- FR-370: append-only enforcement -------------------------------------------------
# See the module docstring for why all three layers are needed and which one each covers.

APPEND_ONLY_FUNCTION = """
CREATE OR REPLACE FUNCTION audit_events_append_only() RETURNS trigger AS $fn$
BEGIN
  RAISE EXCEPTION
    'audit_events is append-only: % rejected (FR-370, 06 R2)', TG_OP
    USING ERRCODE = 'insufficient_privilege',
          HINT = 'Audit events are never updated or deleted. Emit a compensating event.';
END;
$fn$ LANGUAGE plpgsql;
"""

# The application role. NOLOGIN: this migration grants privileges but never provisions a
# credential — a password in a committed migration is exactly what R3 forbids. Deployment
# creates a login role and grants it membership.
APP_ROLE = "gip_app"


def _grant_application_privileges() -> None:
    op.execute(f"""
        DO $do$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
            CREATE ROLE {APP_ROLE} NOLOGIN;
          END IF;
        END
        $do$;
    """)
    op.execute(f"GRANT USAGE ON SCHEMA public TO {APP_ROLE}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON jobs, outbox TO {APP_ROLE}")
    # The whole point: INSERT and SELECT, nothing else.
    op.execute(f"GRANT SELECT, INSERT ON audit_events TO {APP_ROLE}")
    op.execute(f"REVOKE UPDATE, DELETE ON audit_events FROM {APP_ROLE}")
    op.execute("REVOKE UPDATE, DELETE ON audit_events FROM PUBLIC")


def _install_append_only_triggers() -> None:
    op.execute(APPEND_ONLY_FUNCTION)
    op.execute("""
        CREATE TRIGGER audit_events_no_modify
          BEFORE UPDATE OR DELETE ON audit_events
          FOR EACH ROW EXECUTE FUNCTION audit_events_append_only();
    """)
    # Separate trigger, statement-level: row triggers do not fire on TRUNCATE.
    op.execute("""
        CREATE TRIGGER audit_events_no_truncate
          BEFORE TRUNCATE ON audit_events
          FOR EACH STATEMENT EXECUTE FUNCTION audit_events_append_only();
    """)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Enum('ui', 'api', 'schedule', 'system', name='job_source'), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_ref', sa.String(length=512), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('prev_event_hash', sa.String(length=71), nullable=True),
    sa.Column('event_hash', sa.String(length=71), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.CheckConstraint("event_hash ~ '^sha256:[a-f0-9]{64}$'", name=op.f('ck_audit_events_event_hash_format')),
    sa.CheckConstraint("prev_event_hash IS NULL OR prev_event_hash ~ '^sha256:[a-f0-9]{64}$'", name=op.f('ck_audit_events_prev_event_hash_format')),
    sa.CheckConstraint('sequence >= 1', name=op.f('ck_audit_events_sequence_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('event_hash', name='uq_audit_events_event_hash'),
    sa.UniqueConstraint('workspace_id', 'sequence', name='uq_audit_events_workspace_sequence')
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_entity_ref', 'audit_events', ['entity_ref'], unique=False)
    op.create_index('ix_audit_events_workspace_id_at', 'audit_events', ['workspace_id', 'at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('dataset.ingest', 'dataset.validate', 'dataset.profile', 'dataset.derive', 'model.fit', 'model.transparency', 'model.backtest', 'model.compare', 'objective.certify', 'rating.compile', 'rating.regression', 'score.batch', 'dislocation.run', 'optimisation.run', 'gipp.check', 'monitor.run', 'dossier.generate', 'export.regulatory', 'blob.gc', name='job_kind'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('queue', sa.Enum('default', 'compute', 'scoring', 'io', name='job_queue'), nullable=False),
    sa.Column('source', sa.Enum('ui', 'api', 'schedule', 'system', name='job_source'), nullable=False),
    sa.Column('submitted_by', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_budget', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status IN ('succeeded','failed','cancelled')) = (finished_at IS NOT NULL)", name=op.f('ck_jobs_terminal_iff_finished')),
    sa.CheckConstraint("trace_id IS NULL OR trace_id ~ '^[0-9a-f]{32}$'", name=op.f('ck_jobs_trace_id_is_w3c_hex')),
    sa.CheckConstraint('finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at', name=op.f('ck_jobs_finished_after_started')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_queue_status', 'jobs', ['queue', 'status'], unique=False)
    op.create_index('ix_jobs_workspace_id_status', 'jobs', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_jobs_workspace_id_idempotency_key', 'jobs', ['workspace_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('queue', sa.Enum('default', 'compute', 'scoring', 'io', name='job_queue'), nullable=False),
    sa.Column('task', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'published', 'failed', name='outbox_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'published') = (published_at IS NOT NULL)", name=op.f('ck_outbox_published_iff_timestamped')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('job_id', name='uq_outbox_job_id')
    )
    op.create_index('ix_outbox_pending_created_at', 'outbox', ['created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###

    _grant_application_privileges()
    _install_append_only_triggers()


def downgrade() -> None:
    # Triggers first: DROP TABLE would fail against its own append-only guard otherwise.
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_truncate ON audit_events")
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_modify ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS audit_events_append_only()")
    # The role is left in place: it may hold grants on objects this migration did not
    # create, and dropping a role out from under them fails or silently orphans them.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_pending_created_at', table_name='outbox', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('outbox')
    op.drop_index('uq_jobs_workspace_id_idempotency_key', table_name='jobs', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_jobs_workspace_id_status', table_name='jobs')
    op.drop_index('ix_jobs_queue_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_audit_events_workspace_id_at', table_name='audit_events')
    op.drop_index('ix_audit_events_entity_ref', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###

    # Alembic's autogenerated downgrade drops the tables but not the ENUM types it created
    # alongside them, so `downgrade` followed by `upgrade` fails with
    # `DuplicateObjectError: type "job_source" already exists`. FR-435 wants migrations
    # that a deploy can roll back; a rollback that cannot be re-applied is a one-way door.
    for enum_name in ("outbox_status", "job_kind", "job_status", "job_queue", "job_source"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
