"""blob store: content-addressed blobs with reference counts

Revision ID: df69eba49586
Revises: df53696a2682
Create Date: 2026-08-14 18:03:41.044644+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'df69eba49586'
down_revision: str | None = 'df53696a2682'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blobs',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('part_count', sa.Integer(), nullable=True),
    sa.Column('ref_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sha256 ~ '^[a-f0-9]{64}$'", name=op.f('ck_blobs_sha256_is_lowercase_hex')),
    sa.CheckConstraint('bytes >= 0', name=op.f('ck_blobs_bytes_non_negative')),
    sa.CheckConstraint('ref_count >= 0', name=op.f('ck_blobs_ref_count_non_negative')),
    sa.PrimaryKeyConstraint('sha256', name=op.f('pk_blobs'))
    )
    op.create_index('ix_blobs_ref_count_created_at', 'blobs', ['ref_count', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blobs_ref_count_created_at', table_name='blobs')
    op.drop_table('blobs')
    # ### end Alembic commands ###
