"""identity: workspace membership

Revision ID: f3407af4e553
Revises: 6db3b9464e98
Create Date: 2026-08-14 19:07:59.212882+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f3407af4e553'
down_revision: str | None = '6db3b9464e98'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_workspace_members_user_workspace')
    )
    op.create_index('ix_workspace_members_user_id', 'workspace_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_members_user_id', table_name='workspace_members')
    op.drop_table('workspace_members')
    # ### end Alembic commands ###
